### ISSUE TITLE
Participants github handles

### ISSUE THREAD

**Issue by lsetiawan** [ioos/BioData-Training-Workshop#12]
Just wondering if each participant's github handle will be available publicly in github somewhere? so I can add those people to the whitelist for the jupyterhub. Thanks.

**Comment by lsetiawan** [comment]
@emiliom You said previously, that you have this list, could you please send to me so I can start load testing. Thanks.

**Comment by jbosch-noaa** [comment]
Sorry guys ... I meant to ask folks in the last email I sent out.  I sent another one this morning.

**Comment by ebridger** [comment]
Just sent mine to Jen.  But now you have it as well. @ebridger.

**Comment by jbosch-noaa** [comment]
Hah!  I should have said, if you are a GitHub regular I gotcha covered. ;)  Thanks @ebridger

**Comment by emiliom** [comment]
> Sorry guys ... I meant to ask folks in the last email I sent out. I sent another one this morning.

Well, I should've remembered to add it, too, when I reviewed your draft. Sigh.

Thanks for sending out the request, though!

> Just sent mine to Jen. But now you have it as well. @ebridger.

@ebridger Thank you. You're good: you posted your handle in the issue where we're tracking this :+1:

**Comment by emiliom** [comment]
Closing this issue. It's taken care of and/or no longer needed.
