### ISSUE TITLE
Jupyterhub Status

### ISSUE THREAD

**Issue by lsetiawan** [ioos/BioData-Training-Workshop#21]
As of 2/7/18 9:44AM PT
Jupyterhub will be down for service. I am reconfiguring the machine to get ready for the workshop. Like I have warned before, your work in Jupyterhub might be all gone. Sorry for any inconveniences, it will go back up soon. Thanks!

Best,
Don

**Comment by emiliom** [comment]
> Like I have warned before, your work in Jupyterhub might be all gone. Sorry for any inconveniences, it will go back up soon. 

In case anyone gets anxious about that statement from @lsetiawan: he's referring only to personal customizations anyone may have done on JupyterHub. The complete JupyterHub and RStudio setup "we" (ie, mainly Don, Ben, Filipe) have developed is centrally managed and will be restored soon when Don is done with the reconfiguration.

**Comment by emiliom** [comment]
@lsetiawan, can we close this issue?

**Comment by emiliom** [comment]
Ok, closing.
