### ISSUE TITLE
setup binder

### ISSUE THREAD

**Issue by emiliom** [ioos/BioData-Training-Workshop#30]
> I'll set up a binder link so people can also run it online from this repo.

@ocefpaf will set up `binder` on this repo so folks can run Jupyter notebooks online live, with no extra requirements (no JupyterHub or local install). Opening this issue just to identify and track that task.

@ocefpaf, please include all notebooks at https://github.com/ioos/BioData-Training-Workshop/tree/master/notebooks when you set up binder ... though I'm guessing that was your plan anyway.

**Comment by emiliom** [comment]
I tested this. Ran a Python and an R notebook. Both worked.

Initializing binder is pretty slow, but I'm guessing that's because our conda environment is very big.

**Comment by ocefpaf** [comment]
> Initializing binder is pretty slow, but I'm guessing that's because our conda environment is very big.

Only the first time. After the first one the environment is cached and it will load faster. But the cache is removed after a while so we need to "trigger" it a few hours before workshops or demos.

BTW, the Docker image will be about the same size, if not bigger b/c when using envs binder will start its own cached image with miniconda, so only the conda packages are added. When we use a custom Docker image we have the same conda packages, the extra R stuff, and the image with its libs.

**Comment by emiliom** [comment]
>> Initializing binder is pretty slow, but I'm guessing that's because our conda environment is very big.
>
> Only the first time. After the first one the environment is cached and it will load faster. But the cache is removed after a while so we need to "trigger" it a few hours before workshops or demos.

Ah, cool! I didn't know it was cached, so I assumed it was loaded from scratch every time.
