### ISSUE TITLE
Setup server-based R environment in Amazon Cloud

### ISSUE THREAD

**Issue by bbest** [ioos/BioData-Training-Workshop#5]
Hi @lsetiawan,

Which binder are you referring to? I found [BinderHub](https://binderhub.readthedocs.io/en/latest/) by googling "binder and docker", found [binder-project/binder](https://github.com/binder-project/binder), which redirects to [jupyterhub/binderhub](https://github.com/jupyterhub/binderhub), documentation at [BinderHub](https://binderhub.readthedocs.io/en/latest/).

The [mbon-in-box_docker.sh](https://github.com/marinebon/sdg14/blob/gh-pages/technical/mbon-in-box_docker.sh) bash script uses images from hub.docker.com. Here are the associated Dockerfiles, of which only rstudio-shiny is necessary:

- [**rstudio-shiny**](https://github.com/marinebon/docker-rstudio-shiny/blob/master/Dockerfile): RStudio IDE, and Shiny to serve apps.
- [postgis](https://github.com/kartoza/docker-postgis/blob/develop/Dockerfile) (optional): spatial database
- [geoserver](https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile) (optional): mapping engine to serve up tiles
- [www](https://github.com/dockerfile/nginx/blob/master/Dockerfile) (optional): nginx to serve up basic web file content

Please let me know what I can do to help. Would love to get access to the Amazon instance and figure out how user permissions and Github login are managed.

**Comment by emiliom** [comment]
Thanks for getting this going, @bbest. @lsetiawan is working on the AWS instance, and if we're lucky he'll have the first live version by Friday.

FYI, Don and I use PostGIS and GeoServer, in general. Let us know if that's something you'd use actively for workshop tutorials, and we can work with you to see what we can do.

**Comment by lsetiawan** [comment]
@bbest when I tried building https://github.com/marinebon/docker-rstudio-shiny/blob/master/Dockerfile, I get an error:

```
preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/library/tcltk/libs/tcltk.so':
  libtcl8.6.so: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package ‘geoR’
* removing ‘/usr/local/lib/R/site-library/geoR’
Error in install.packages(pkgs = f, lib = lib, repos = if (isMatchingFile(f)) NULL else rep,  : 
  installation of package ‘geoR’ had non-zero exit status
```

Do you have a docker image that's already built where I can pull from? Thanks.

**Comment by bbest** [comment]
Hi @lsetiawan,

Here's the preferred `Dockerfile`:

```dockerfile
FROM rocker/geospatial:latest
RUN export ADD=shiny && bash /etc/cont-init.d/add
```

This gets the latest Dockerfile from [github.com/rocker-org/geospatial](https://github.com/rocker-org/geospatial) and adds Shiny server to the built image. I was able to get this working using temporary path `~/Desktop/rstudio-shiny/Dockerfile`:

```bash
# build image
docker build -t rstudio-shiny:3.4.3 ~/Desktop/rstudio-shiny

# tag with username and version
docker tag rstudio-shiny:3.4.3 bdbest/rstudio-shiny:3.4.3-geospatial

# push to docker hub (https://hub.docker.com/r/bdbest/rstudio-shiny/tags/)
docker login
docker push bdbest/rstudio-shiny:3.4.3-geospatial

# run container locally
docker run --name "rstudio-shiny" \
  -p 8787:8787 -p 3838:3838 \
  -e USER=user -e PASSWORD=password \
  -e ROOT=TRUE \
  -d -t bdbest/rstudio-shiny:3.4.3-geospatial
```

Note that you could simply run the last `docker run` command to use the image I just built and pushed, but should change the USER and PASSWORD. This command doesn't deal with virtual volumes to data folders, nor addition of other users (which would be cool to know how to do for any Github user).

Then browse to http://localhost:8787 and you should see a prompt for login:

![image](https://user-images.githubusercontent.com/2837257/35200293-29a01596-fec0-11e7-8dc4-5e26559e7aea.png)

Including RStudio and Shiny in the same container is much preferred over seperate so any packages subsequently installed in RStudio are available in the Shiny apps served.

Please let me know if this works on your end. We can visit the optional PostGIS and GeoServer later.

**Comment by lsetiawan** [comment]
@bbest Have checked out the Jupyterhub url that I sent last Friday? and Thanks for the above. Do you know how to debug shiny app?

**Comment by bbest** [comment]
Hi @lsetiawan,

## RStudio Session working :)

Nice work! I was able to login using my Github username `bbest` via the bit.ly URL you sent Friday and launch an RStudio Session. This is fantastic! And means we should be able to do the majority of workshop. Shiny apps are extra.

Please see bolded numbered (eg **1.**) questions (in _italics_) below...

![image](https://user-images.githubusercontent.com/2837257/35238170-97115de6-ff61-11e7-9b92-5d4b915f41e9.png)

## Persistent user storage?

This opens to a URL suggestive of a unique user space, 
`https://a495e...0f9b0-638...21.us-west-2.elb.amazonaws.com/user/bbest/rstudio`, but but a different username `jovyan` appears in upper right (vs `bbest`).

![image](https://user-images.githubusercontent.com/2837257/35238205-abab0540-ff61-11e7-99d9-ba429d354b7b.png)

**1.** _Will files stored in the user's home directory persist between sessions and be unique to that user?_

## Shiny apps not working, ports?

The Shiny apps don't appear to work. These can be launched in one of two ways:

1. **Local**. In a local RStudio session using the `shiny` R package, you can run `shiny::runApp('test_app')` where `test_app` is the directory containing the shiny application files (eg `app.R` or `ui.R` & `server.R`).

2. **Server**.  Shiny server can run applications defined by the `site_dir` (defaults to `/srv/shiny-server` per [Shiny Server docs](http://docs.rstudio.com/shiny-server/#default-configuration)), so could be mapped to docker hosting server folder (eg `/data/shiny-apps`) at runtime like so:

```bash
docker run --name "rstudio-shiny" \
  -p 8787:8787 -p 3838:3838 \
  -e USER=user -e PASSWORD=password \
  -e ROOT=TRUE \
  -v /data/shiny-apps:/srv/shiny-server \
  -v /data/shiny-log:/var/log/shiny-server \
  -d -t bdbest/rstudio-shiny:3.4.3-geospatial
```

### Local shiny app failure

I can try running a test shiny app by going to File > New File > Shiny Web App:

![image](https://user-images.githubusercontent.com/2837257/35238232-c0e49fca-ff61-11e7-8d54-881d96e3968e.png)

Then type in a folder name for the app:

![image](https://user-images.githubusercontent.com/2837257/35238280-df3b5536-ff61-11e7-940f-4cb0345728e4.png)

And Run the app by clicking the green play button while editing the `app.R` file in RStudio:

![image](https://user-images.githubusercontent.com/2837257/35238295-e70a328c-ff61-11e7-8da3-8c62c896e25e.png)

This runs the shiny app launching command in the R Console:

```r
shiny::runApp('test_app')
```

Which shows the following message in the console:

```
Loading required package: shiny
Listening on http://127.0.0.1:4842
```

After I allow popups in my browser, I see the URL `https://a495e...0f9b0-638...21.us-west-2.elb.amazonaws.com/user/bbest/rstudio/p/4842/`, so it appears port 4842 is attempting to map to the `/p/4842/` URL, but the page then shows:

```
/p/4842/ not found
```

**2.** _So how do ports work on the Amazon instance to get Local and Server methods of shiny apps to work?_

**3.** _Can we setup Shiny server to use a folder so a persistent URL can be used to share a shiny app?_

**4.** _Can I get access to this server and be shown how the login works?_

**Comment by lsetiawan** [comment]
Thanks for the thorough assessment @bbest.

> Persistent user storage?

Yes, each user storage is persistent, everyone will have the same username. This is built from the Dockerfile. How the system knows the username is that each pod is labeled uniquely based on their github username. Are you familiar with Kubernetes?

> Server. Shiny server can run applications defined by the site_dir (defaults to /srv/shiny-server per Shiny Server docs), so could be mapped to docker hosting server folder (eg /data/shiny-apps) at runtime like so

This way works great. Right now the problem is Jupyter Notebook is not proxying where the shiny app port is properly. The people at Jupyter is working on this. I have gotten in touch with Jupyter developer and he is working on a solution, but he is having trouble debugging shiny apps. Please see https://github.com/jupyterhub/nbrsessionproxy/issues/24. If you have any experience debugging shiny apps within rstudio web server, it would be awesome. 

> So how do ports work on the Amazon instance?

Everything is currently routed through port 443, the front end is using jupyterhub. Like I have said before, I am following this setup: http://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/index.html

> Can we setup Shiny server to use a folder so a persistent URL can be used to share a shiny app?

I am not familiar with shiny app, so I don't quite understand what this question refers to.

> Can I get access to this server and be shown how the login works?

All the logins are through github, and based on the magic of `nbrsessionproxy` you don't need to login to `RStudio`. The actual server is just mostly controlling kubernetes. If you want to know details, please refer to http://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/index.html. The big setup is actually gonna be within the [Dockerfile](https://github.com/ioos/BioData-Training-Workshop/blob/master/Dockerfile) This gets deployed for each user.

**Comment by lsetiawan** [comment]
@ocefpaf Are you familar with `nbserverproxy` at all?

**Comment by ocefpaf** [comment]
> @ocefpaf Are you familiar with nbserverproxy at all?

Sorry, no. (Actually never heard of it before.)

**Comment by lsetiawan** [comment]
@ocefpaf Okay. No worries. It's python library for jupyter notebook server to proxy web services. A combination of [`nbserverproxy`](https://github.com/jupyterhub/nbserverproxy) and [`nbrsessionproxy`](https://github.com/jupyterhub/nbrsessionproxy) make it possible for us to have RStudio within Jupyter Notebook.

**Comment by bbest** [comment]
hi @lsetiawan,

I think you explained well the port mapping issue in https://github.com/jupyterhub/nbrsessionproxy/issues/24, so hopefully the JupyterHub experts can chime with a suggestion for getting the Shiny apps to work.

I'm not that familiar with Kubernetes and the documentation at http://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/index.html is quite extensive, so not sure where to begin. I don't see `nbserverproxy` mentioned anywhere there, but do see [Authentication — Zero to JupyterHub with Kubernetes 0.4 documentation](http://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/authentication.html) showing how to setup the `config.yaml` to use Github.

I don't understand how the JupyterHub instance enabled with RStudio that you pointed me to with the bit.ly URL gets spun up from simply the [Dockerfile](https://github.com/ioos/BioData-Training-Workshop/blob/master/Dockerfile) where I don't see any reference to R/Rstudio/Shiny?

Thank you for your patience as I work through understanding the mechanics here.

**Comment by lsetiawan** [comment]
@bbest No worries. It is a complex, but very scalable setup, but once things click, everything will make sense.

1. Like I have mentioned before, UC Berkley is using this setup for MOOC. At least the Python part. The R still have a lot of work for it to work prefectly, but the people at Jupyter would like to really get this working. I just don't have enough experience to understand the whole proxy thing within Jupyter notebook server to really contribute much at this point. 

2. Kubernetes to put it into simple terms is a manager for containerized applications, in this case jupyter notebook within docker. So Kubernetes is basically just performing docker run each time a user is logged in and pressed start server, it automatically spin it up on a machine that has the most resources within the cluster. 

3. All of those 'pods` or `docker container` is routed through a load balancer in aws, this is the long ugly url (I used the bitly right now to shorten it so it's easier to type/remember). Each pod is created from an images hosted within my docker hub account. The Dockerfile in this repo is actually an expansion to the [Base Dockerfile](https://github.com/lsetiawan/jnrstud-minimal/blob/master/Dockerfile)

4. Behind the scenes, `nbrsessionproxy` is used to proxy ports to the rstudio. Most of this pod setup is configured within `config.yml`.

I hope that makes sense somewhat. There are of course a lot of detail, the above is just a simple summary of how things work. Thanks.

**Comment by bbest** [comment]
Ah ok, now I see the necessary lines in [lsetiawan/jnrstud-minimal:**Dockerfile**](https://github.com/lsetiawan/jnrstud-minimal/blob/master/Dockerfile) for RStudio and Shiny:

```dockerfile
FROM rocker/geospatial:latest
RUN export ADD=shiny && bash /etc/cont-init.d/add
```

The proxy'ing is very confusing, but now at least I'm noticing that [`nbrsessionproxy`](https://github.com/jupyterhub/nbrsessionproxy) is the "Jupyter extension for running an RStudio rsession proxy" and in their `README.md` it seems to suggest:

```dockerfile
# install nbrsessionproxy: Jupyter extensions for running an RStudio rsession proxy
RUN pip install git+https://github.com/jupyterhub/nbrsessionproxy && \
  # install the extensions for all users on the system
  jupyter serverextension enable  --py --sys-prefix nbrsessionproxy && \
  jupyter nbextension     install --py --sys-prefix nbrsessionproxy && \
  jupyter nbextension     enable  --py --sys-prefix nbrsessionproxy
```

whereas your [lsetiawan/jnrstud-minimal:**Dockerfile**](https://github.com/lsetiawan/jnrstud-minimal/blob/master/Dockerfile) has some extra stuff:

```dockerfile
RUN pip install --no-cache-dir \
         git+https://github.com/jupyterhub/nbrsessionproxy.git@b8a6518f92cd08f18031d7733d4db0dc07ee7c8d \
         nbserverproxy==0.3.2 && \
    jupyter serverextension enable --sys-prefix --py nbserverproxy && \
    jupyter serverextension enable --sys-prefix --py nbrsessionproxy && \
    jupyter nbextension install    --sys-prefix --py nbrsessionproxy && \
    jupyter nbextension enable     --sys-prefix --py nbrsessionproxy
````

Did you already try the latest default version, or was there a reason to use a specific git commit and need to first enable `nbserverproxy`?

Or maybe you need to seperately install and enable `nbserverproxy` per https://github.com/jupyterhub/nbrsessionproxy/issues/14#issuecomment-338801837?:

```dockerfile
# install nbrsessionproxy: Jupyter extensions for running an RStudio rsession proxy
RUN pip install git+https://github.com/jupyterhub/nbrsessionproxy && \
  # install nbserverproxy: Jupyter notebook server extension to proxy web services
  pip install git+https://github.com/jupyterhub/nbserverproxy && \
  # enable nbserverproxy for all users on the system
  jupyter serverextension enable --py --sys-prefix nbserverproxy && \
  # enable nbextension for all users on the system
  jupyter serverextension enable  --py --sys-prefix nbrsessionproxy && \
  jupyter nbextension     install --py --sys-prefix nbrsessionproxy && \
  jupyter nbextension     enable  --py --sys-prefix nbrsessionproxy
```

**Comment by lsetiawan** [comment]
> Did you already try the latest default version, or was there a reason to use a specific git commit and need to first enable nbserverproxy?

Yea, the specific git commit is currently the one that works, for some reason, the latest one seems to be broken.

**Comment by lsetiawan** [comment]
Here's what the JupyterHub developer said about the problem we're having, which is same issue they're having currently.

```
Yuvi Panda Jan 19 12:19
@lsetiawan yeah, I think that's what we ran into as well
@lsetiawan I guess we need to figure out how to get shiny to use a different URL path to work under nbrsessionproxy
```

**Comment by bbest** [comment]
## Skip Shiny

Ok, I'm just noticing this issue https://github.com/jupyter/notebook/issues/1484 "support for Shiny R" which alludes to bigger structural issues involving web sockets that I don't follow. We have plenty to share at the workshop, so can skip Shiny apps.

## Latest R

I'm surprised to see "R version 3.4.0" in the RStudio Console since `rocker/geospatial:latest` in [lsetiawan/jnrstud-minimal:**Dockerfile**](https://github.com/lsetiawan/jnrstud-minimal/blob/master/Dockerfile) should install "R version 3.4.3", per [rocker-org/geospatial](https://github.com/rocker-org/geospatial). If you're using https://hub.docker.com/r/bdbest/rstudio-shiny/tags/, I recommend the "3.4.3-geospatial" from yesterday over "R-3.4-geospatial" from 7 months ago.

## Installing R packages

Not sure how this RStudio instance is getting launched (`docker run` command?), but the default path for installing packages `/usr/local/lib/R/site-library` is not writeable (but should be if using `docker run` argument of `-e ROOT=TRUE`). Here's a workaround for installing an R package, for instance [`rasterVis`](https://oscarperpinan.github.io/rastervis/):

### Default R package install not working

If you go to the Packages pane in RStudio and try to install a package via GUI, you will get an endless loop of clicking Yes or cancelling with No to this prompt "Would you like to create a personal library '/usr/local/lib/R/site-library' to install packages into?":

![image](https://user-images.githubusercontent.com/2837257/35249397-b1b1c436-ff86-11e7-8619-6671537c9918.png)

Or if using function `install.packages()` in the R Console:

```r
install.packages('rasterVis')
```

Response:

```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Would you like to use a personal library instead?  (y/n) y
trying URL 'https://mran.microsoft.com/snapshot/2017-06-04/src/contrib/rasterVis_0.41.tar.gz'
Content type 'application/octet-stream' length 40749 bytes (39 KB)
==================================================
downloaded 39 KB

Error: ERROR: no permission to install to directory ‘/usr/local/lib/R/site-library’
```

### Workaround to install R packages

We can set an R package library path within the user home directory:

```R
# setup writeable R package folder
dir_pkgs <- "~/R_packages"
dir.create(dir_pkgs)
.libPaths(dir_pkgs)

# install an R package
install.packages('rasterVis')
```

**Comment by lsetiawan** [comment]
@bbest Now that I have figured out how all of the pieces work together with Python and R, I am planning to modify the Dockerfile to be based on a jupyter base, so that things are cleaner, and R packages will be managed by conda rather than having root packages, hence the problem with installing packages, and conda packages. This way we can always ask @ocefpaf if we need any packages in conda, else you still be able to install them within the terminal without permission issue. 

My next PR will contain changes described above. Btw, the conda rbase is version `3.4.2` though. https://anaconda.org/r/r-base, @ocefpaf is there a 3.4.3 that you can package? Thanks!

**Comment by bbest** [comment]
Hmm... so will the conda method replace the RStudio you get from simply using the following in your Dockerfile?

```dockerfile
FROM rocker/geospatial:latest
```

I advocate this method over replacing with conda, since many useful packages are installed (especially spatial) along with their system dependent software that I'm not sure are easily available through conda. Here's the recursive list of included rocker Dockerfiles to get a sense of all the packages and dependencies installed:

- [geospatial](https://github.com/rocker-org/geospatial/blob/master/Dockerfile)
- [verse](https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile)
- [tidyverse](https://github.com/rocker-org/rocker-versioned/blob/master/tidyverse/Dockerfile)
- [rstudio](https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile)
- [r-ver](https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/Dockerfile)

If you still want to go the conda route, here are a few potentially relevant conda packages:

* [R Tidyverse :: Anaconda Cloud](https://anaconda.org/r/r-tidyverse)
* [R Spatial :: Anaconda Cloud](https://anaconda.org/r/r-spatial)
* [R Sp :: Anaconda Cloud](https://anaconda.org/r/r-sp)

**Comment by ocefpaf** [comment]
> My next PR will contain changes described above. Btw, the conda rbase is version `3.4.2` though. 

That is r-base from the default channel, conda-forge is still using 3.4.1

> https://anaconda.org/r/r-base, @ocefpaf is there a 3.4.3 that you can package? Thanks!

Unfortunately that is not an easy task b/c R breaks ABI compatibility at every micro version. Also, there is not the concept of `noarch` like in python. That would force us to re-compile all the packages and it would take a long time. Can you manage with `defaults` 3.4.2? Or conda-forge's version 3.4.1?

---
Edit: see part of the update r-base discussion here https://github.com/conda-forge/r-base-feedstock/pull/27#issuecomment-351115809

**Comment by jbosch-noaa** [comment]
@samuelbosch - here is another issue thread you may want to read up on.

**Comment by ocefpaf** [comment]
@bbest I'm looking at the r packages listed in the Dockerfile from https://github.com/ioos/BioData-Training-Workshop/issues/5#issuecomment-359635102 and there are tons of packages, some even redundant like `RNetCDF` and `ncdf4`, I guess that the latter is preferred. I wonder if all of those will be used in the workshop.

Some are already in conda-forge and others are a low hanging fruit to add, but if we could get a more streamlined version of the packages (also in a single list so I don't have to navigate all those Dockerfiles) it would help me a lot :smile:

**Comment by lsetiawan** [comment]
Here's what I got so far for R packages: (Please add to list)

- [X] r-base 3.4.1
- [X] r-irkernel 0.8.11
- [X] rstudio 1.0.153
- [X] r-classint 0.1_24
- [X] r-crosstalk 1.0.0
- [X] r-deldir 0.1_14
- [X] r-devtools 1.13.2
- [X] r-dplyr 0.7.4
- [X] r-dt 0.2
- [X] r-dygraphs 1.1.1.4
- [X] r-finch 0.1.0
- [X] r-forcats 0.2.0
- [X] r-geor 1.7_5.2
- [X] r-geosphere 1.5_5
- [X] r-ggplot2 2.2.1
- [X] r-glue 1.1.1
- [X] r-gstat 1.1_5
- [X] r-hdf5r 1.0.0
- [X] r-htmlwidgets 0.9
- [X] r-knitr 1.16
- [X] r-leaflet 1.1.0
- [X] r-leaflet.extras 0.2
- [X] r-lidr 1.4.0
- [X] r-lubridate 1.6.0
- [X] r-magrittr 1.5
- [X] r-mapdata 2.2_6
- [X] r-mapedit 0.3.2
- [X] r-maptools 0.9_2
- [X] r-mapview 2.2.0
- [X] r-ncdf4 1.16
- [X] r-obistools 0.0.5
- [X] r-osmar 1.1-7
- [X] r-plotly 4.7.1
- [X] r-proj4 1.0_8
- [X] r-purrr 0.2.3
- [X] r-randomfields 3.1.50
- [X] r-randomfieldsutils 0.3.25
- [X] r-raster 2.5_8
- [X] r-rastervis 0.43
- [X] r-rcolorbrewer 1.1_2
- [X] r-readr 1.1.1
- [X] r-readxl 1.0.0
- [X] r-rgdal 1.2_16
- [X] r-rgeos 0.3_26
- [X] r-ritis 0.7.0
- [X] r-rlang 0.1.2
- [X] r-rmarkdown 1.6
- [X] r-rnetcdf 1.9_1
- [X] r-robis 1.0.0
- [X] r-rvest 0.3.2
- [X] r-sf 0.6_0
- [X] r-shiny 1.0.3
- [X] r-sp 1.2-7
- [X] r-spacetime 1.2_0
- [X] r-spatial 7.3_11
- [X] r-spatstat 1.54_0
- [X] r-spatstat.data 1.2_0
- [X] r-spatstat.utils 1.8_0
- [X] r-spdep 0.6_13
- [X] r-stringr 1.2.0
- [X] r-taxize 0.9.0
- [X] r-taxizesoap 0.1.0.99
- [X] r-tibble 1.3.3
- [X] r-tidyr 0.7.1
- [X] r-tidyverse 1.1.1
- [X] r-uuid 0.1_2
- [X] r-wikidatar 1.4.0
- [X] r-wikipedir 1.5.0
- [X] r-wikitaxa 0.2.0
- [ ] r-grid ([grid](https://cran.r-project.org/src/contrib/Archive/grid/) is too old to be installed in modern T :: `obistools` dependency.)
- [ ] r-tmap (dependency [stack needs `r-v8`](https://github.com/ocefpaf/staged-recipes/tree/missing_v8/recipes) and that is not package yet.)

**Comment by lsetiawan** [comment]
Placing a note here from @samuelbosch:
The only thing I would need is that the course participants should be able to install/re-install latest versions of packages especially obistools using `devtools::install_github("iobis/obistools")` or a similar command.

**Comment by ocefpaf** [comment]
@lsetiawan I added all the packages I got from @bbest's [geospatial Dockerfile](https://github.com/rocker-org/geospatial/blob/master/Dockerfile) and the ones from #4. Those unchecked are not in conda-forge, the ones checked are in conda-forge and I added the current version available.

Note that the if you add those to the env file right now it won't work. I am re-rendering some of those build them for r 3.4., see https://github.com/conda-forge/r-taxizesoap-feedstock/pull/1, https://github.com/conda-forge/r-gstat-feedstock/pull/1, https://github.com/conda-forge/r-finch-feedstock/pull/1, https://github.com/conda-forge/r-spacetime-feedstock/pull/1, and https://github.com/conda-forge/r-ssoap-feedstock/pull/1 (there will be more. I'll send a PR updating the env once I finish.)

BTW, I am planning on adding the `master` version of `obistools` but it would be nice to have a release to point to before the workshop.

**Comment by lsetiawan** [comment]
Thanks @ocefpaf! Wow! You really did a lot!

**Comment by ocefpaf** [comment]
> You really did a lot!

Packaging is a thankless and laborious job. But it is slightly less taxing than setting up a jupyterhub server :smile:

**Comment by yuvipanda** [comment]
@lsetiawan ok, try out https://mybinder.org/v2/gh/yuvipanda/binder-1/master?urlpath=rstudio I think it should work. Can you test out various shiny features and lmk if they all work?

I'll make PRs to the appropriate repos shortly.

**Comment by yuvipanda** [comment]
ok, https://github.com/jupyterhub/nbserverproxy/pull/17 and https://github.com/jupyterhub/nbrsessionproxy/pull/25 are the PRs I made to get shiny working with rstudio in a JupyterHub context. The link in my previous comment should still work.

LMK if there are bugs in the RStudio integration available in the link I provided, and I'll try fixing them. I'll try to get these two PRs merged and a release made in the next few days.

**Comment by emiliom** [comment]
My apologies for not being able to participate in this discussion this week, and for this brief comment.

@ocefpaf, thanks so much for your fantastic efforts on R packaging for conda forge!

I've tried to follow up the discussion. With the big caveat that I'm not an R person and don't have a good understanding of R library use and packaging on the "pure R", non-conda side of things, I just want to make sure that if we do go to a primarily conda route, that @bbest's concerns are well addressed and he's satisfied with the solution. After all, he's our R expert here!

**Comment by jbosch-noaa** [comment]
Thanks for your input @emiliom.  I also want to make sure that the other R experts (@samuelbosch, and @albenson-usgs) are ok with our conda solution.

**Comment by AbbyBenson** [comment]
I'll be honest. I don't really understand what all of this is for so ¯\_(ツ)_/¯

**Comment by jbosch-noaa** [comment]
@albenson-usgs  - Are the R packages they are pre-loading good?  I gave them the list you sent me via email but I just want to make sure you didn't think of anything else. :)

**Comment by AbbyBenson** [comment]
Ah! Yes. The list looks good. The box next to obistools doesn't look to be checked but I have no idea what that actually means. So I'm good!

**Comment by ocefpaf** [comment]
> I'll be honest. I don't really understand what all of this is for so ¯\_(ツ)_/¯

@albenson-usgs `conda` is an agnostic package manager that makes it easier to install software on OS X, Linux, and Windows with the same, or at least similar, instructions, aking it perfect for workshops like this one (while improving interoperability and reproducibility at the same time).

`conda` also makes it easier for @lsetiawan to set jupyterhub up by facilitating the creation of the environment where the packages will be installed.

It would be nice for us to have some code examples that people expected to work during the workshop so we can set up some tests for the packages stack we are adding to the conda environment.

> Ah! Yes. The list looks good. The box next to obistools doesn't look to be checked but I have no idea what that actually means. So I'm good!

Means that the package is not available on conda yet :smile:
Like I mention in https://github.com/ioos/BioData-Training-Workshop/issues/5#issuecomment-360643475 I will add it soon, just working on some of its dependencies first and, b/c that one is install from latest source, it will probably require an update right before the workshop to include its latest changes.

**Comment by AbbyBenson** [comment]
Oh ok, yes that makes complete sense. Thank you for all your help with this!

**Comment by bbest** [comment]
This is now resolved by https://github.com/ioos/BioData-Training-Workshop/issues/8#issuecomment-361349580 😃

**Comment by yuvipanda** [comment]
Glad to be of use :)

**Comment by bbest** [comment]
Yes, THANK YOU SO MUCH @yuvipanda for the critical PRs that got RStudio, Rmarkdown & Shiny playing nicely with JupyterHub. We're super stoked!

* [Fix asynchronity issues with websockets by yuvipanda · Pull Request #17 · jupyterhub/nbserverproxy](https://github.com/jupyterhub/nbserverproxy/pull/17)
* [Cleanup code + make Shiny work by yuvipanda · Pull Request #25 · jupyterhub/nbrsessionproxy](https://github.com/jupyterhub/nbrsessionproxy/pull/25)
