### ISSUE TITLE
Rstudio Issues

### ISSUE THREAD

**Issue by lsetiawan** [ioos/BioData-Training-Workshop#8]
1) When using the latest `nbrsessionproxy` and `nbserverproxy` with RStudio from Conda I get:
```
[E 16:06:45.794 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/opt/conda/lib/python3.6/site-packages/tornado/routing.py", line 251, in finish
        self.delegate.finish()
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 2096, in finish
        self.execute()
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 2116, in execute
        **self.handler_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 21, in __init__
        assert WebSocketHandlerMixin in bases
    AssertionError
```

2) Current fix is to use the versions below:
`git+https://github.com/jupyterhu/nbrsessionproxy.git@b8a6518f92cd08f18031d7733d4db0dc07ee7c8d \` and `nbserverproxy==0.3.2`
    **However, this does not include the latest changes that Jupyterhub developers have made that allows shiny to work**

What seemed to work is using the rocker/geospatial as base and installing conda on top, following https://github.com/yuvipanda/binder-1/blob/master/Dockerfile. This allows R users to be able to install dev R repos also. *Currently, I am working on deploying this into JupyterHub*

**Comment by lsetiawan** [comment]
When executing `devtools::install_github("iobis/obistools")` within the conda rstudio setup. I get this error:
```
ERROR: dependencies ‘data.tree’, ‘sf’ are not available for package ‘obistools’
* removing ‘/opt/conda/lib/R/library/obistools’
```

**Comment by ocefpaf** [comment]
@lsetiawan I'm updating `sf`, but it may take a while b/c the latest version depends on package from https://github.com/conda-forge/staged-recipes/pull/4849 (there are a lot of packages there!).

xref.: https://github.com/conda-forge/r-sf-feedstock/pull/1

**Comment by lsetiawan** [comment]
Okay! Update. This is for R users. I finally got the RStudio working, this is built from `rocker/geospatial` docker image. Shiny seems to work also! I have also tested @bbest install script, and that worked with no problem whatsoever, all packages installed nicely. So I think I am gonna keep it this way so the local version of R is the same as the cloud version. 

Sorry @ocefpaf for doing all that hardwork packaging, and now I don't think I'll end up using it. 😞 Though we still can put them in an environment file! Thanks.

FYI, there are some more tweaks I need to make before the docker image is stable, so hang on on trying anything on the cloud. I'll let you guys know when I'm done, so ya'll can start testing things. 😄

**Comment by ocefpaf** [comment]
No problem @lsetiawan. Please take the easiest path to set up jupyterhub.

I'll still go ahead with the packaging to provide an alternative way to install the env (and I'll probably use that later in the IOOS Data Demo Center too).

**Comment by lsetiawan** [comment]
@bbest I've setup the RStudio on the cloud. Please try your R stuff there. Thanks!

**Comment by bbest** [comment]
Hey @lsetiawan,

Everything works great!

Here's what I tried:

- Went to the URL you emailed https://*.cloudmaven.org
- Logged in via Github and Started Server: https://*.cloudmaven.org/user/bbest/tree
- New -> RStudio Session: https://*.cloudmaven.org/user/bbest/rstudio/
- Tested **Rmarkdown**: File -> New File -> Rmarkdown... with defaults. Saved locally and knitted to html (Knit button), which appeared after allowing site around Pop-Up Blocker in Google Chrome browser: https://*.cloudmaven.org/user/bbest/rstudio/files/test_Rmarkdown.html  🎉
- Tested **Shiny** app: File -> New File -> Shiny Web App... Works at https://*.cloudmaven.org/user/bbest/rstudio/p/5622/  🎉
- Installed R **packages** via:
  
  ```r
  url <- "https://raw.githubusercontent.com/ioos/BioData-Training-Workshop/master/install-R-packages.R"
  source(url)
  ```
  - Took 10 minutes to complete, and finished successfully 🎉 

Fantastic work!

**Comment by lsetiawan** [comment]
Thanks so much for testing the waters on the R side of things @bbest. I'm glad it all works now 😄
