### ISSUE TITLE
Jupyterhub domain

### ISSUE THREAD

**Issue by lsetiawan** [ioos/BioData-Training-Workshop#9]
What should the ioos workshop jupyterhub domain set at?

**Comment by emiliom** [comment]
It's not obvious that we'll assign it a (sub)domain name, since it'll be a short-term resource. I know that w/o it the url is awful, but can we by with bitly shortened url's?

**Comment by lsetiawan** [comment]
It already has a bit.ly url. Thanks.

**Comment by lsetiawan** [comment]
I am using a `cloudmaven.org` subdomain for the workshop. Thanks. See email for details.

**Comment by lsetiawan** [comment]
This is all configured now. Closing.
